### YamlMime:ManagedReference
apiRules:
- include:
    uidRegex: ^Piot\.Tick

- include:
    uidRegex: ^Piot\.Clog

- include:
    uidRegex: ^Piot\.MonotonicTime

- include:
    uidRegex: ^Piot\.Nimble\.*

- exclude:
    uidRegex: ^Piot\..*
