### YamlMime:ManagedReference
apiRules:
  - include:
      uidRegex: ^Nimble\.Client$
      type: Namespace
  - include:
      uidRegex: ^Nimble\.Host$
      type: Namespace

  - exclude:
      uidRegex: ^Nimble\..*$
      type: Namespace


  - include:
      uidRegex: ^Piot\.Tick$
      type: Namespace
  - include:
      uidRegex: ^Piot\.Clog$
      type: Namespace
  - include:
      uidRegex: ^Piot\.MonotonicTime$
      type: Namespace

  - exclude:
      uidRegex: ^Piot\..*$
      type: Namespace
